[package]
name = "achronyme-dsp"
version = "0.6.1"
edition = "2021"

[dependencies]
achronyme-types = { path = "../achronyme-types" }
rustfft = "6.1"
num-complex = "0.4"

[dev-dependencies]
approx = "0.5"
